#! /bin/bash

export CONFIG_64BIT=m
export CONFIG_ALPHA=m
export CONFIG_ALPHA=m
export CONFIG_ARCH_32BIT_USTAT_F_TINODEexport=m
export CONFIG_ARCH_FLATMEM_ENABLE=m
export CONFIG_ARCH_HAS_CURRENT_STACK_POINTER=m
export CONFIG_ARCH_HAS_DEVMEM_IS_ALLOWED=m
export CONFIG_ARCH_HAVE_NMI_SAFE_CMPXCHG=m
export CONFIG_ARCH_MIGHT_HAVE_PC_PARPORT=m
export CONFIG_ARCH_MIGHT_HAVE_PC_SERIO=m
export CONFIG_ARCH_NO_PREEMPT=m
export CONFIG_ARCH_NO_SG_CHAIN=m
export CONFIG_ARCH_ROCKCHIP=m
export CONFIG_ARCH_SELECT_MEMORY_MODEL=m
export CONFIG_ARCH_SELECT_MEMORY_MODEL=m
export CONFIG_ARCH_SPARSEMEM_ENABLE=m
export CONFIG_ARCH_USE_CMPXCHG_LOCKREF=m
export CONFIG_ARCH_WANT_IPC_PARSE_VERSION=m
export CONFIG_ARM64=m
export CONFIG_AUDIT_ARCH=m
export CONFIG_AUTO_IRQ_AFFINITY=m
export CONFIG_CONTIG_ALLOC=m
export CONFIG_CPU_NO_EFFICIENT_FFS=m
export CONFIG_DEVMEM=m
export CONFIG_DMADEVICES=m
export CONFIG_DMA_ENGINE=m
export CONFIG_DMA=m #???
export CONFIG_DMA_OPS=m
export CONFIG_DMA_SHARED_BUFFER=m
export CONFIG_DRM_DISPLAY_HDMI_HELPER=m
export CONFIG_DRM_DISPLAY_HELPER=m
export CONFIG_DRM_FBDEV_EMULATION=m
export CONFIG_FRAMEBUFFER_CONSOLE_DETECT_PRIMARY=m
export CONFIG_VT=m
export CONFIG_DRM_BOCHS=m
export CONFIG_DRM_BRIDGE=y
###
export CONFIG_DRM_CIRRUS_QEMU=m

export CONFIG_DRM_TTM=m
export CONFIG_DRM_TTM_HELPER=m
export CONFIG_DRM_FBDEV_GENERIC_SETUP=m
export CONFIG_DRM_FBDEV_LEAK_PHYS_SMEM=m
export CONFIG_DRM_GEM_SHMEM_HELPER=m
export CONFIG_DRM_KMS_HELPER=m
export CONFIG_DRM_MALI_DISPLAY=m
export CONFIG_DRM_MALI=m
export CONFIG_DRM_PANEL=y
export CONFIG_DRM_PANEL_BRIDGE=y
export CONFIG_DRM_PANEL_ORIENTATION_QUIRKS=m
export CONFIG_DRM_PANFROST=m
export CONFIG_DRM_ROCKCHIP=m
export CONFIG_DRM_SHMEM_HELPER=m
export CONFIG_DRM_VIRTIO_GPU_KMS=y
export CONFIG_DRM_VKMS=m
export CONFIG_DRM_VRAM_HELPER=m
###
export CONFIG_DRM_QXL=m
export CONFIG_DRM_UDL=m
export CONFIG_DRM_AST=m
export CONFIG_DRM_MGAG200=m
export CONFIG_DRM_NOUVEAU=m
export CONFIG_DRM_NOUVEAU_BACKLIGHT=y
export CONFIG_DRM_FBDEV_OVERALLOC=100

export CONFIG_DW_DMAC_PCI=m
export CONFIG_EXCLUSIVE_SYSTEM_RAM=m
export CONFIG_EXPERIMENTAL=m
export CONFIG_EXPERT=m
export CONFIG_FB_BOOT_VESA_SUPPORT=m
export CONFIG_FB_CORE=m
export CONFIG_FB_DEFERRED_IO=m
export CONFIG_FB_SIMPLE=m
export CONFIG_FB_SYS_COPYAREA=m
export CONFIG_FB_SYS_FILLRECT=m
export CONFIG_FB_SYS_IMAGEBLIT=m
export CONFIG_FB_SYSMEM_FOPS=m
export CONFIG_FB_SYSMEM_HELPERS_DEFERRED=m
export CONFIG_FB_SYSMEM_HELPERS=m
export CONFIG_FB_SIMPLE=m
export CONFIG_FB_SYS_FILLRECT=m
export CONFIG_FB_SYS_IMAGEBLIT=m
export CONFIG_FB_VESA=m
export CONFIG_FORCE_PCI=m
export CONFIG_FRAMEBUFFER_CONSOLE_DETECT_PRIMARY=m
export CONFIG_FRAMEBUFFER_CONSOLE_LEGACY_ACCELERATION=n
export CONFIG_FRAMEBUFFER_CONSOLE=m
export CONFIG_VT_HW_CONSOLE_BINDING=m
export CONFIG_HW_CONSOLE=m
export CONFIG_TTY=m
export CONFIG_CRC32=m
export CONFIG_BITREVERSE=m
export CONFIG_FONT_SUPPORT=m
export CONFIG_FONT_AUTOSELECT=m
export CONFIG_FONT_8x16=m
export CONFIG_FONT_8x8=m
export CONFIG_FRAMEBUFFER_CONSOLE_ROTATION=n
export CONFIG_GENERIC_CPU_VULNERABILITIES=m
export CONFIG_GENERIC_IRQ_PROBE=m
export CONFIG_GENERIC_IRQ_SHOW=m
export CONFIG_GENERIC_LIB_DEVMEM_IS_ALLOWED=m
export CONFIG_GENERIC_PCI_IOMAP=m
export CONFIG_GENERIC_SMP_IDLE_THREAD=m
export CONFIG_HAS_DMA=m
export CONFIG_HAS_IOPORT=m
export CONFIG_HAVE_ARCH_AUDITSYSCALL=m
export CONFIG_HAVE_ASM_MODVERSIONS=m
export CONFIG_HAVE_MOD_ARCH_SPECIFIC=m
export CONFIG_HAVE_PCI=m
export CONFIG_HAVE_PCI=m
export CONFIG_HAVE_PCSPKR_PLATFORM=m
export CONFIG_HAVE_PERF_EVENTS=m
export CONFIG_HDMI=m
export CONFIG_HDMI=m
export CONFIG_I2C=m
export CONFIG_I2C=m
export CONFIG_INPUT=m
export CONFIG_IRQ_DOMAIN=m
export CONFIG_KCMP=m
export CONFIG_KCMP=m
export CONFIG_LIBNVDIMM=m
export CONFIG_LOCK_MM_AND_FIND_VMA=m
export CONFIG_MEMORY_HOTPLUG=m
export CONFIG_MEMORY_HOTREMOVE=m
export CONFIG_MMU_GATHER_NO_RANGE=m
export CONFIG_MMU=m
export CONFIG_MODULES_USE_ELF_RELA=m
export CONFIG_NEED_DMA_MAP_STATE=m
export CONFIG_NEED_SG_DMA_LENGTH=m
export CONFIG_NET=m
export CONFIG_n=m
export CONFIG_ODD_RT_SIGACTION=m
export CONFIG_OLD_SIGSUSPEND=m
export CONFIG_PCI_DOMAINS=m
export CONFIG_PCI=m
export CONFIG_PCI_SYSCALL=m
export CONFIG_QEMU_FW_CFG=m
export CONFIG_ROCKCHIP_ANALOGIX_DP=m
export CONFIG_ROCKCHIP_CDN_DP=m
export CONFIG_ROCKCHIP_DW_HDMI=m
export CONFIG_ROCKCHIP_DW_MIPI_DSI=m
export CONFIG_ROCKCHIP_INNO_HDMI=m
export CONFIG_ROCKCHIP_LVDS=m
export CONFIG_ROCKCHIP_VOP2=m
export CONFIG_ROCKCHIP_VOP=m
export CONFIG_RT_MUTEXES=m
export CONFIG_SELECT_MEMORY_MODEL=m
export CONFIG_SPARC32=m
export CONFIG_SPARSEMEM_EXTREME=m
export CONFIG_SPARSEMEM=m
export CONFIG_SPARSEMEM_MANUAL=m
export CONFIG_STRICT_DEVMEM=m
export CONFIG_SYNC_FILE=m
export CONFIG_SYNC_FILE=m
export CONFIG_VDPA=m
export CONFIG_VP_VD=m
export CONFIG_VIDEO_CMDLINE=m
export CONFIG_VIDEO_NOMODESET=m
export CONFIG_VIRT_DRIVERS=m

export CONFIG_VIRTIO_ANCHOR=m
export CONFIG_VIRTIO_BALLON=m
export CONFIG_VIRTIO_BLK=m
export CONFIG_VIRTIO_DMA_BUF=m
export CONFIG_VIRTIO_DMA_SHARED_BUFFER=m
export CONFIG_VIRTIO_GPU=m
export CONFIG_VIRTIO_INPUT=m
export CONFIG_VIRTIO_IOMMU=m
export CONFIG_VIRTIO=m
export CONFIG_VIRTIO_MEM=m
export CONFIG_VIRTIO_MENU=m
export CONFIG_VIRTIO_MMIO=m
export CONFIG_VIRTIO_NET=m
export CONFIG_VIRTIO_PCI_LEGACY_DEV=m

export CONFIG_VIRTIO_PCI_MODERN_DEV=m
export CONFIG_VIRTIO_PMEM=m
export CONFIG_VIRTIO_RING=m
export CONFIG_VIRTIO_SCSI=m
export CONFIG_VIRTIO_VDPA=m
export CONFIG_VIRTIO_PCI_LIB=m
export CONFIG_VIRTIO_PCI_LIB_LEGACY=m
export CONFIG_VIRTIO_PCI_LEGACY=y
export CONFIG_VIRTIO_INPUT=m
########################################################
export CONFIG_PCI=y
export CONFIG_VIRTIO_PCI=y
export CONFIG_PCI_HOST_GENERIC=y
export CONFIG_PCIEPORT=y
export CONFIG_AHCI=y
export CONFIG_DRM=y
export CONFIG_DRM_VIRTIO_GPU=y
#######################################################
export CONFIG_MACVLAN=y
export CONFIG_NLMON=y
#export CONFIG_VT_HW_CONSOLE_BINDING=y
export CONFIG_SERIAL_AMBA_PL011=y
export CONFIG_SERIAL_AMBA_PL011_CONSOLE=y
export CONFIG_VIRTIO_CONSOLE=y
export CONFIG_HW_RANDOM=y
export CONFIG_HW_RANDOM_VIRTIO=y
export CONFIG_DRM=y
export CONFIG_DRM_VIRTIO_GPU=y
export CONFIG_RTC_CLASS=y
export CONFIG_RTC_DRV_PL031=y
export CONFIG_VIRTIO_PCI=y
export CONFIG_VIRTIO_MMIO=y
export CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES=y
export CONFIG_MAILBOX=y
########################################################
export CONFIG_MD=m
export CONFIG_FS_IOMAP=m
export CONFIG_SBITMAP=m
export CONFIG_DMA_ENGINE=m
export CONFIG_DMADEVICES=m
export CONFIG_BLOCK_HOLDER_DEPRECATED=m
export CONFIG_BLK_DEV_DM_BUILTIN=m
export CONFIG_BLK_MQ_STACKING=m
export CONFIG_INTERVAL_TREE=m
export CONFIG_TMPFS_INODE64=y
export CONFIG_FS_POSIX_ACL=m

export CONFIG_BLK_MQ_VIRTIO=y
export CONFIG_VIRTIO_VSOCKETS=m
export CONFIG_VIRTIO_VSOCKETS_COMMON=m
export CONFIG_NET_9P_VIRTIO=m
export CONFIG_SCSI_VIRTIO=m
export CONFIG_VIRTIO_NET=m
export CONFIG_VIRTIO_CONSOLE=m
export CONFIG_HW_RANDOM_VIRTIO=m
export CONFIG_DRM_VIRTIO_GPU=m
export CONFIG_DRM_VIRTIO_GPU_KMS=y

export CONFIG_CRYPTO_DEV_VIRTIO=m
export CONFIG_ZONE_DMA=m

export CONFIG_QRTR=m
export CONFIG_AES_CE_BLK=m
export CONFIG_AES_CE_CIPHER=m
export CONFIG_POLYVAL=m
export CONFIG_EVDEV=m
export CONFIG_POLYVAL_GENERIC=m
export CONFIG_GHASH_CE=m
export CONFIG_GF128MUL=m
export CONFIG_SHA2_CE=m
export CONFIG_SHA256_ARM64=m
export CONFIG_SHA1_CE=m
export CONFIG_VIRTIO_INPUT=m
export CONFIG_LOOP=m
export CONFIG_EFI_PSTORE=m
export CONFIG_DM_MOD=m
export CONFIG_64BIT=m
export CONFIG_MIGRATION=m
export CONFIG_NUMA=m
export CONFIG_COMPACTION=m
export CONFIG_CMA=m
export CONFIG_MEMORY_HOTPLUG=m
export CONFIG_ARCH_ENABLE_MEMORY_HOTPLUG=m
export CONFIG_MEMORY_HOTREMOVE=m
export CONFIG_ARCH_ENABLE_MEMORY_HOTREMOVE=m
export CONFIG_SPARSEMEM=m
export CONFIG_SPARSEMEM_MANUAL=m
export CONFIG_SPARSEMEM_VMEMMAP=m
export CONFIG_SPARSEMEM_VMEMMAP_ENABLE=m
export CONFIG_ARCH_HAS_PTE_DEVMAP=m
export CONFIG_CONFIGFS=m
export CONFIG_NFNETLINK=m
export CONFIG_QEMU_FW_CFG=m
export CONFIG_IP_TABLES=m
export CONFIG_X_TABLES=m
export CONFIG_AUTOFS4=m
export CONFIG_EXT4=m
export CONFIG_CRC16=m
export CONFIG_MBCACHE=m
export CONFIG_JBD2=m
export CONFIG_CRC32C_GENERIC=m
export CONFIG_VIRTIO_BLK=m
export CONFIG_VIRTIO_GPU=m
export CONFIG_VIRTIO_DMA_BUF=m
export CONFIG_SRM_SHMEM_HELPER=m
export CONFIG_XHCI_PCI=m
export CONFIG_XHCI_HCD=m
export CONFIG_DRM_KMS_HELPER=m
export CONFIG_CRCT10DIF_CE=m
export CONFIG_CRCT10DIF_COMMON=m
export CONFIG_USBCORE=m
export CONFIG_DRM=m
export CONFIG_VIRTIO_NET=m
export CONFIG_USB_COMMON=m
export CONFIG_NET_FAILOVER=m
export CONFIG_FAILOVER=m
export CONFIG_VIRTIO_MMIO=m


###############################################################



HEADERS=$1
CWD=$PWD
OUTDIR=${CWD}
CPUS=$(($(nproc)))

git clone --depth=1 https://github.com/torvalds/linux
#cp ${CWD}/config/.config.old linux/
cd linux

echo "CONFIG_DRM_VIRTIO_GPU=y" >> arch/arm64/configs/defconfig
echo "CONFIG_AHCI=y" >> arch/arm64/configs/defconfig
echo "CONFIG_PCIEPORT=y" >> arch/arm64/configs/defconfig
echo "CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES=y" >> arch/arm64/configs/defconfig

#yes "" | make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- oldconfig
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig

BUILD="$(sed -n 's|^.*\s\+\(\S\+\.\S\+\.\S\+\)\s\+Kernel Configuration$|\1|p' .config)"
echo "${BUILD}" > ${CWD}/config/release
KERNELDIR="KERNEL-${BUILD}"
mkdir -p "${KERNELDIR}"

# yes "" | make -j ${CPUS} ARCH=arm64 KERNELRELEASE="${BUILD}" CROSS_COMPILE=aarch64-linux-gnu- Image.gz modules dtbs
make -j ${CPUS} ARCH=arm64 KERNELRELEASE="${BUILD}" CROSS_COMPILE=aarch64-linux-gnu- Image.gz modules dtbs

env PATH=$PATH make KERNELRELEASE="${BUILD}" ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- INSTALL_MOD_PATH=${KERNELDIR} modules_install
if [ "$HEADERS" == "yes" ]; then
  make headers_install INSTALL_HDR_PATH=${KERNELDIR}
fi
mkdir -p "${KERNELDIR}/boot/" "${KERNELDIR}/lib/linux-image-${BUILD}/"rockchip/
echo "ffffffffffffffff B The real System.map is in the linux-image-<version>-dbg package" > "${KERNELDIR}/boot/System.map-${BUILD}"
cp .config "${KERNELDIR}/boot/config-${BUILD}"
cp arch/arm64/boot/Image.gz "${KERNELDIR}/boot/vmlinuz-${BUILD}"
cp -r arch/arm64/boot/dts/rockchip/*.dtb "${KERNELDIR}/lib/linux-image-${BUILD}/"rockchip/
ARCHIVE="kernel-$(sed -n 's|^.*\s\+\(\S\+\.\S\+\.\S\+\)\s\+Kernel Configuration$|\1|p' .config)$(sed -n 's|^CONFIG_LOCALVERSION=\"\(.*\)\"$|\1|p' .config).zip"
cd "${KERNELDIR}"
find lib -type l -exec rm {} \;
zip -q -r "${ARCHIVE}" *
if [ "${OUTDIR}" != "" ]; then
  if [ "${OUTDIR: -1}" != "/" ]; then
      OUTDIR+="/"
  fi
else
  if [ "${REALUSER}" = "root" ]; then
      OUTDIR="/root/"
  else
      OUTDIR="/home/${REALUSER}/"
  fi
fi
chown "${REALUSER}:${REALUSER}" "${ARCHIVE}"
cd ${CWD}/linux
mv "${KERNELDIR}/${ARCHIVE}" "${OUTDIR}"
rm -rf "${KERNELDIR}"
cd ${CWD}
#rm -rf linux

echo "1" > ${CWD}/config/kernel_status
