#!/bin/bash

CONFIG_FILE="arch/arm64/configs/defconfig"

# Liste der Konfigurationsvariablen, die auf 'n' gesetzt werden sollen
CONFIG_VARS=(
    CONFIG_ARCH_ACTIONS
    CONFIG_ARCH_SUNXI
    CONFIG_ARCH_ALPINE
    CONFIG_ARCH_APPLE
    CONFIG_ARCH_BCM
    CONFIG_ARCH_BCM2835
    CONFIG_ARCH_BCM_IPROC
    CONFIG_ARCH_BCMBCA
    CONFIG_ARCH_BRCMSTB
    CONFIG_ARCH_BERLIN
    CONFIG_ARCH_EXYNOS
    CONFIG_ARCH_SPARX5
    CONFIG_ARCH_K3
    CONFIG_ARCH_LG1K
    CONFIG_ARCH_HISI
    CONFIG_ARCH_KEEMBAY
    CONFIG_ARCH_MEDIATEK
    CONFIG_ARCH_MESON
    CONFIG_ARCH_MVEBU
    CONFIG_ARCH_NXP
    CONFIG_ARCH_LAYERSCAPE
    CONFIG_ARCH_MXC
    CONFIG_ARCH_S32
    CONFIG_ARCH_MA35
    CONFIG_ARCH_NPCM
    CONFIG_ARCH_QCOM
    CONFIG_ARCH_REALTEK
    CONFIG_ARCH_RENESAS
    CONFIG_ARCH_SEATTLE
    CONFIG_ARCH_INTEL_SOCFPGA
    CONFIG_ARCH_STM32
    CONFIG_ARCH_SYNQUACER
    CONFIG_ARCH_TEGRA
    CONFIG_ARCH_TESLA_FSD
    CONFIG_ARCH_SPRD
    CONFIG_ARCH_THUNDER
    CONFIG_ARCH_THUNDER2
    CONFIG_ARCH_UNIPHIER
    CONFIG_ARCH_VEXPRESS
    CONFIG_ARCH_VISCONTI
    CONFIG_ARCH_XGENE
    CONFIG_ARCH_ZYNQMP
)

# Öffne das Konfigurationsfile und setze die gewünschten Variablen auf 'n'
for var in "${CONFIG_VARS[@]}"; do
    sed -i "s/^${var}=y$/${var}=n/" "$CONFIG_FILE"
done

# Ausgabe zur Bestätigung
echo "Alle Konfigurationsvariablen außer CONFIG_ARCH_ROCKCHIP wurden auf 'n' gesetzt."
